// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.9.2
// source: roadside_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoadsideServiceType int32

const (
	RoadsideServiceType_motel   RoadsideServiceType = 0
	RoadsideServiceType_food    RoadsideServiceType = 1
	RoadsideServiceType_parking RoadsideServiceType = 2
	RoadsideServiceType_carWash RoadsideServiceType = 3
)

// Enum value maps for RoadsideServiceType.
var (
	RoadsideServiceType_name = map[int32]string{
		0: "motel",
		1: "food",
		2: "parking",
		3: "carWash",
	}
	RoadsideServiceType_value = map[string]int32{
		"motel":   0,
		"food":    1,
		"parking": 2,
		"carWash": 3,
	}
)

func (x RoadsideServiceType) Enum() *RoadsideServiceType {
	p := new(RoadsideServiceType)
	*p = x
	return p
}

func (x RoadsideServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoadsideServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_roadside_service_proto_enumTypes[0].Descriptor()
}

func (RoadsideServiceType) Type() protoreflect.EnumType {
	return &file_roadside_service_proto_enumTypes[0]
}

func (x RoadsideServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoadsideServiceType.Descriptor instead.
func (RoadsideServiceType) EnumDescriptor() ([]byte, []int) {
	return file_roadside_service_proto_rawDescGZIP(), []int{0}
}

type RoadsideService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type        RoadsideServiceType `protobuf:"varint,2,opt,name=type,proto3,enum=api.RoadsideServiceType" json:"type,omitempty"`
	Title       string              `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string              `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Location    *Geo                `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Address     string              `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Images      []string            `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	Phone       []string            `protobuf:"bytes,8,rep,name=phone,proto3" json:"phone,omitempty"`
	Email       []string            `protobuf:"bytes,9,rep,name=email,proto3" json:"email,omitempty"`
	Keys        []string            `protobuf:"bytes,10,rep,name=keys,proto3" json:"keys,omitempty"`
	Lat         float64             `protobuf:"fixed64,11,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon         float64             `protobuf:"fixed64,12,opt,name=lon,proto3" json:"lon,omitempty"`
}

func (x *RoadsideService) Reset() {
	*x = RoadsideService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roadside_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoadsideService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoadsideService) ProtoMessage() {}

func (x *RoadsideService) ProtoReflect() protoreflect.Message {
	mi := &file_roadside_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoadsideService.ProtoReflect.Descriptor instead.
func (*RoadsideService) Descriptor() ([]byte, []int) {
	return file_roadside_service_proto_rawDescGZIP(), []int{0}
}

func (x *RoadsideService) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoadsideService) GetType() RoadsideServiceType {
	if x != nil {
		return x.Type
	}
	return RoadsideServiceType_motel
}

func (x *RoadsideService) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoadsideService) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoadsideService) GetLocation() *Geo {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *RoadsideService) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RoadsideService) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *RoadsideService) GetPhone() []string {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *RoadsideService) GetEmail() []string {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *RoadsideService) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *RoadsideService) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *RoadsideService) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type RoadsideServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RoadsideServiceRequest) Reset() {
	*x = RoadsideServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roadside_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoadsideServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoadsideServiceRequest) ProtoMessage() {}

func (x *RoadsideServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roadside_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoadsideServiceRequest.ProtoReflect.Descriptor instead.
func (*RoadsideServiceRequest) Descriptor() ([]byte, []int) {
	return file_roadside_service_proto_rawDescGZIP(), []int{1}
}

func (x *RoadsideServiceRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RoadsideServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RoadsideServiceResponse) Reset() {
	*x = RoadsideServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roadside_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoadsideServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoadsideServiceResponse) ProtoMessage() {}

func (x *RoadsideServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roadside_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoadsideServiceResponse.ProtoReflect.Descriptor instead.
func (*RoadsideServiceResponse) Descriptor() ([]byte, []int) {
	return file_roadside_service_proto_rawDescGZIP(), []int{2}
}

func (x *RoadsideServiceResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoadsideServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FindRoadsideServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Location *Geo     `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Keys     []string `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	Limit    uint32   `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset   uint32   `protobuf:"varint,10,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *FindRoadsideServiceRequest) Reset() {
	*x = FindRoadsideServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roadside_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRoadsideServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRoadsideServiceRequest) ProtoMessage() {}

func (x *FindRoadsideServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roadside_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRoadsideServiceRequest.ProtoReflect.Descriptor instead.
func (*FindRoadsideServiceRequest) Descriptor() ([]byte, []int) {
	return file_roadside_service_proto_rawDescGZIP(), []int{3}
}

func (x *FindRoadsideServiceRequest) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *FindRoadsideServiceRequest) GetLocation() *Geo {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *FindRoadsideServiceRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *FindRoadsideServiceRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindRoadsideServiceRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FindRoadsideServiceResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64                              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt   string                              `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   string                              `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Location    *FindRoadsideServiceResult_ShortGeo `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Type        uint32                              `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Title       string                              `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description string                              `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Keys        []string                            `protobuf:"bytes,11,rep,name=keys,proto3" json:"keys,omitempty"`
	Images      []string                            `protobuf:"bytes,12,rep,name=images,proto3" json:"images,omitempty"`
	Phone       []string                            `protobuf:"bytes,13,rep,name=phone,proto3" json:"phone,omitempty"`
	Email       []string                            `protobuf:"bytes,14,rep,name=email,proto3" json:"email,omitempty"`
	Owner       *FindRoadsideServiceResult_Owner    `protobuf:"bytes,17,opt,name=owner,proto3" json:"owner,omitempty"`
	Likes       int32                               `protobuf:"varint,18,opt,name=likes,proto3" json:"likes,omitempty"`
	Dislikes    int32                               `protobuf:"varint,19,opt,name=dislikes,proto3" json:"dislikes,omitempty"`
}

func (x *FindRoadsideServiceResult) Reset() {
	*x = FindRoadsideServiceResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roadside_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRoadsideServiceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRoadsideServiceResult) ProtoMessage() {}

func (x *FindRoadsideServiceResult) ProtoReflect() protoreflect.Message {
	mi := &file_roadside_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRoadsideServiceResult.ProtoReflect.Descriptor instead.
func (*FindRoadsideServiceResult) Descriptor() ([]byte, []int) {
	return file_roadside_service_proto_rawDescGZIP(), []int{4}
}

func (x *FindRoadsideServiceResult) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindRoadsideServiceResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FindRoadsideServiceResult) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *FindRoadsideServiceResult) GetLocation() *FindRoadsideServiceResult_ShortGeo {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *FindRoadsideServiceResult) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *FindRoadsideServiceResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FindRoadsideServiceResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FindRoadsideServiceResult) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *FindRoadsideServiceResult) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *FindRoadsideServiceResult) GetPhone() []string {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *FindRoadsideServiceResult) GetEmail() []string {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *FindRoadsideServiceResult) GetOwner() *FindRoadsideServiceResult_Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *FindRoadsideServiceResult) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *FindRoadsideServiceResult) GetDislikes() int32 {
	if x != nil {
		return x.Dislikes
	}
	return 0
}

type FindRoadsideServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoadsideServices []*FindRoadsideServiceResult `protobuf:"bytes,1,rep,name=RoadsideServices,proto3" json:"RoadsideServices,omitempty"`
	Found            uint64                       `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *FindRoadsideServiceResponse) Reset() {
	*x = FindRoadsideServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roadside_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRoadsideServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRoadsideServiceResponse) ProtoMessage() {}

func (x *FindRoadsideServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roadside_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRoadsideServiceResponse.ProtoReflect.Descriptor instead.
func (*FindRoadsideServiceResponse) Descriptor() ([]byte, []int) {
	return file_roadside_service_proto_rawDescGZIP(), []int{5}
}

func (x *FindRoadsideServiceResponse) GetRoadsideServices() []*FindRoadsideServiceResult {
	if x != nil {
		return x.RoadsideServices
	}
	return nil
}

func (x *FindRoadsideServiceResponse) GetFound() uint64 {
	if x != nil {
		return x.Found
	}
	return 0
}

type FindRoadsideServiceResult_ShortGeo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type    uint32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Address string  `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Lat     float64 `protobuf:"fixed64,5,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon     float64 `protobuf:"fixed64,6,opt,name=lon,proto3" json:"lon,omitempty"`
}

func (x *FindRoadsideServiceResult_ShortGeo) Reset() {
	*x = FindRoadsideServiceResult_ShortGeo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roadside_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRoadsideServiceResult_ShortGeo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRoadsideServiceResult_ShortGeo) ProtoMessage() {}

func (x *FindRoadsideServiceResult_ShortGeo) ProtoReflect() protoreflect.Message {
	mi := &file_roadside_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRoadsideServiceResult_ShortGeo.ProtoReflect.Descriptor instead.
func (*FindRoadsideServiceResult_ShortGeo) Descriptor() ([]byte, []int) {
	return file_roadside_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *FindRoadsideServiceResult_ShortGeo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindRoadsideServiceResult_ShortGeo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindRoadsideServiceResult_ShortGeo) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *FindRoadsideServiceResult_ShortGeo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *FindRoadsideServiceResult_ShortGeo) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *FindRoadsideServiceResult_ShortGeo) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type FindRoadsideServiceResult_Owner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FindRoadsideServiceResult_Owner) Reset() {
	*x = FindRoadsideServiceResult_Owner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roadside_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRoadsideServiceResult_Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRoadsideServiceResult_Owner) ProtoMessage() {}

func (x *FindRoadsideServiceResult_Owner) ProtoReflect() protoreflect.Message {
	mi := &file_roadside_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRoadsideServiceResult_Owner.ProtoReflect.Descriptor instead.
func (*FindRoadsideServiceResult_Owner) Descriptor() ([]byte, []int) {
	return file_roadside_service_proto_rawDescGZIP(), []int{4, 1}
}

func (x *FindRoadsideServiceResult_Owner) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindRoadsideServiceResult_Owner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_roadside_service_proto protoreflect.FileDescriptor

var file_roadside_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x0b, 0x63,
	0x61, 0x72, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc3, 0x02, 0x0a, 0x0f, 0x52,
	0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x6f,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e,
	0x22, 0x28, 0x0a, 0x16, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x17, 0x52, 0x6f,
	0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x98, 0x01, 0x0a, 0x1a, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x24, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x6f, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0xf0, 0x04, 0x0a, 0x19, 0x46,
	0x69, 0x6e, 0x64, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x43, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x47, 0x65,
	0x6f, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18,
	0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x0d, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x3a, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6b, 0x65, 0x73, 0x18, 0x12, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x13, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x73, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x1a, 0x80, 0x01,
	0x0a, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x47, 0x65, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e,
	0x1a, 0x2b, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x7f, 0x0a,
	0x1b, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x10,
	0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x10, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x2a, 0x44,
	0x0a, 0x13, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x6d, 0x6f, 0x74, 0x65, 0x6c, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x70, 0x61,
	0x72, 0x6b, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x57, 0x61,
	0x73, 0x68, 0x10, 0x03, 0x32, 0xf2, 0x02, 0x0a, 0x16, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x44, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x61,
	0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x6f,
	0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x04, 0x46, 0x69, 0x6e, 0x64, 0x12, 0x1f, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3e, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3e, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x45, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x6f, 0x61, 0x64, 0x73, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_roadside_service_proto_rawDescOnce sync.Once
	file_roadside_service_proto_rawDescData = file_roadside_service_proto_rawDesc
)

func file_roadside_service_proto_rawDescGZIP() []byte {
	file_roadside_service_proto_rawDescOnce.Do(func() {
		file_roadside_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_roadside_service_proto_rawDescData)
	})
	return file_roadside_service_proto_rawDescData
}

var file_roadside_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_roadside_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_roadside_service_proto_goTypes = []interface{}{
	(RoadsideServiceType)(0),                   // 0: api.RoadsideServiceType
	(*RoadsideService)(nil),                    // 1: api.RoadsideService
	(*RoadsideServiceRequest)(nil),             // 2: api.RoadsideServiceRequest
	(*RoadsideServiceResponse)(nil),            // 3: api.RoadsideServiceResponse
	(*FindRoadsideServiceRequest)(nil),         // 4: api.FindRoadsideServiceRequest
	(*FindRoadsideServiceResult)(nil),          // 5: api.FindRoadsideServiceResult
	(*FindRoadsideServiceResponse)(nil),        // 6: api.FindRoadsideServiceResponse
	(*FindRoadsideServiceResult_ShortGeo)(nil), // 7: api.FindRoadsideServiceResult.ShortGeo
	(*FindRoadsideServiceResult_Owner)(nil),    // 8: api.FindRoadsideServiceResult.Owner
	(*Geo)(nil),                                // 9: api.Geo
}
var file_roadside_service_proto_depIdxs = []int32{
	0,  // 0: api.RoadsideService.type:type_name -> api.RoadsideServiceType
	9,  // 1: api.RoadsideService.location:type_name -> api.Geo
	9,  // 2: api.FindRoadsideServiceRequest.location:type_name -> api.Geo
	7,  // 3: api.FindRoadsideServiceResult.location:type_name -> api.FindRoadsideServiceResult.ShortGeo
	8,  // 4: api.FindRoadsideServiceResult.owner:type_name -> api.FindRoadsideServiceResult.Owner
	5,  // 5: api.FindRoadsideServiceResponse.RoadsideServices:type_name -> api.FindRoadsideServiceResult
	2,  // 6: api.RoadsideServiceService.Get:input_type -> api.RoadsideServiceRequest
	4,  // 7: api.RoadsideServiceService.Find:input_type -> api.FindRoadsideServiceRequest
	1,  // 8: api.RoadsideServiceService.Create:input_type -> api.RoadsideService
	1,  // 9: api.RoadsideServiceService.Update:input_type -> api.RoadsideService
	2,  // 10: api.RoadsideServiceService.Delete:input_type -> api.RoadsideServiceRequest
	5,  // 11: api.RoadsideServiceService.Get:output_type -> api.FindRoadsideServiceResult
	6,  // 12: api.RoadsideServiceService.Find:output_type -> api.FindRoadsideServiceResponse
	3,  // 13: api.RoadsideServiceService.Create:output_type -> api.RoadsideServiceResponse
	3,  // 14: api.RoadsideServiceService.Update:output_type -> api.RoadsideServiceResponse
	3,  // 15: api.RoadsideServiceService.Delete:output_type -> api.RoadsideServiceResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_roadside_service_proto_init() }
func file_roadside_service_proto_init() {
	if File_roadside_service_proto != nil {
		return
	}
	file_cargo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_roadside_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoadsideService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roadside_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoadsideServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roadside_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoadsideServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roadside_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRoadsideServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roadside_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRoadsideServiceResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roadside_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRoadsideServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roadside_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRoadsideServiceResult_ShortGeo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roadside_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRoadsideServiceResult_Owner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_roadside_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_roadside_service_proto_goTypes,
		DependencyIndexes: file_roadside_service_proto_depIdxs,
		EnumInfos:         file_roadside_service_proto_enumTypes,
		MessageInfos:      file_roadside_service_proto_msgTypes,
	}.Build()
	File_roadside_service_proto = out.File
	file_roadside_service_proto_rawDesc = nil
	file_roadside_service_proto_goTypes = nil
	file_roadside_service_proto_depIdxs = nil
}
